name: build
on:
  push:
    paths-ignore:
      - 'README.md'
  deployment:
    branches:
      - master

jobs:
  pakcer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        git-version:
          - master
          - v1.2.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install packer

      - name: Install Ansible
        run: |
          python3 -m pip install ansible

      - name: Retrieve Ansible playbooks
        run: |
          git clone https://github.com/ansible-playbooks-centos7/redmica_install.git
          git clone https://github.com/ansible-playbooks-centos7/system.git

      - name: Create Google application credentials file
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_ENCODED }} | base64 -d > credentials.json

      - name: Execute pakcer build command
        run: |
          IMAGE_NAME="redmica-golden-image-${{ matrix.git-version}}-`date --date \"9 hours\" \"+%Y-%m%d-%H%M%S\"`"
          IMAGE_NAME=$(echo $IMAGE_NAME | sed 's/\.//g')

          packer build \
          -var "git_version=${{ matrix.git-version }}" \
          -var "image_name=${IMAGE_NAME}" \
          -var "project_id=buoyant-world-263612" \
          -var "source_image_family=centos-7" \
          -var "ssh_username=packer" \
          -var "zone=asia-northeast2-a" \
          build.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: 'credentials.json'

      - name: Show Go version
        run: |
          go version

      - name: Show Packer version
        run: |
          packer version

      - name: Show Ansible version
        run: |
          ansible --version
